name: Windows x64

on:
  push:
  pull_request:

jobs:
  release-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Release x64
        run: msbuild neo\doom3.sln /m /v:minimal /p:Configuration=Release /p:Platform=x64

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: Doom3BFG-Release-x64
          path: build/x64/Release/Doom3BFG.exe
          if-no-files-found: error
